pipeline {
    agent none

    environment {
        AWS_REGION = "us-east-2"
        AWS_BUCKET = "imagebuilder-jenkins-testing-use2"
    }

    options {
        timestamps()
        ansiColor('xterm')

        // Cancel the pipeline if it runs for more than one hour.
        timeout(
            time: 1,
            unit: "HOURS"
        )
    }

    // Build the images each weekday between 05:00-05:59.
    triggers {
        cron 'H 5 * * 1-5'
    }

    stages {

        stage("Build AWS Images") {
            failFast false

            environment {
                RHN_CREDS = credentials("rhn-credentials-mhayden")
            }

            parallel {
                stage('Fedora 32') {
                    agent { label "f32cloudbase && aws" }
                    environment {
                        AWS_CREDS = credentials('aws-credentials-osbuildci')
                    }
                    steps {
                        sh "./build-aws-image.sh"
                    }
                }
                stage('RHEL 8 CDN') {
                    agent { label "rhel8cloudbase && aws" }
                    environment {
                        AWS_CREDS = credentials('aws-credentials-osbuildci')
                    }
                    steps {
                        sh "./build-aws-image.sh"
                    }
                }
            }
        }

        stage("Build OpenStack Images") {
            failFast false

            parallel {
                stage('Fedora 31') {
                    agent { label "f31cloudbase && psi" }
                    environment {
                        OPENSTACK_CREDS = credentials("psi-openstack-clouds-yaml")
                    }
                    steps {
                        retry(3) {
                            sh "./build-openstack-image.sh"
                        }

                    }
                }
                stage('Fedora 32') {
                    agent { label "f32cloudbase && psi" }
                    environment {
                        OPENSTACK_CREDS = credentials("psi-openstack-clouds-yaml")
                    }
                    steps {
                        retry(3) {
                            sh "./build-openstack-image.sh"
                        }
                    }
                }
                stage('RHEL 8 CDN') {
                    agent { label "rhel8cloudbase && psi" }
                    environment {
                        OPENSTACK_CREDS = credentials("psi-openstack-clouds-yaml")
                    }
                    steps {
                        retry(3) {
                            sh "./build-openstack-image.sh"
                        }
                    }
                }
                // NOTE(mhayden): RHEL 8.3 is only available in PSI for now.
                stage('RHEL 8.3 Nightly') {
                    agent { label "rhel83cloudbase && psi" }
                    environment {
                        OPENSTACK_CREDS = credentials("psi-openstack-clouds-yaml")
                    }
                    steps {
                        retry(3) {
                            sh "./build-openstack-image.sh"
                        }
                    }
                }
            }
        }

    }
}
