pipeline {
    agent none

    environment {
        AWS_REGION = "us-east-2"
        AWS_BUCKET = "imagebuilder-jenkins-testing-use2"
    }

    options {
        timestamps()
        ansiColor('xterm')
        // Cancel the pipeline if it runs for more than three hours.
        timeout(
            time: 1,
            unit: "HOURS"
        )
    }

    stages {

        stage("Build AWS Images") {
            failFast false

            parallel {
                // Fedora 31's osbuild-composer cannot upload to AWS.
                // stage('Fedora 31') {
                //     agent { label "fedora31 && psi" }
                //     environment {
                //         AWS_CREDS = credentials('aws-credentials-osbuildci')
                //     }
                //     steps {
                //         sh "./build-aws-image.sh"
                //     }
                // }
                stage('Fedora 32') {
                    agent { label "fedora32 && psi" }
                    environment {
                        AWS_CREDS = credentials('aws-credentials-osbuildci')
                    }
                    steps {
                        sh "./build-aws-image.sh"
                    }
                }
                stage('RHEL 8 CDN') {
                    agent { label "rhel8 && psi" }
                    environment {
                        AWS_CREDS = credentials('aws-credentials-osbuildci')
                    }
                    steps {
                        sh "./build-aws-image.sh"
                    }
                }
            }
        }

        stage("Build OpenStack Images") {
            failFast false

            parallel {
                stage('Fedora 31') {
                    agent { label "fedora31 && psi" }
                    environment {
                        OPENSTACK_CREDS = credentials("psi-openstack-clouds-yaml")
                    }
                    steps {
                        sh "./build-openstack-image.sh"
                    }
                }
                stage('Fedora 32') {
                    agent { label "fedora32 && psi" }
                    environment {
                        OPENSTACK_CREDS = credentials("psi-openstack-clouds-yaml")
                    }
                    steps {
                        sh "./build-openstack-image.sh"
                    }
                }
                stage('RHEL 8 CDN') {
                    agent { label "rhel8 && psi" }
                    environment {
                        OPENSTACK_CREDS = credentials("psi-openstack-clouds-yaml")
                    }
                    steps {
                        sh "./build-openstack-image.sh"
                    }
                }
                // NOTE(mhayden): RHEL 8.3 is only available in PSI for now.
                stage('RHEL 8.3 Nightly') {
                    agent { label "rhel83 && psi" }
                    environment {
                        OPENSTACK_CREDS = credentials("psi-openstack-clouds-yaml")
                    }
                    steps {
                        sh "./build-openstack-image.sh"
                    }
                }
            }
        }

    }
}
