name = "imagebuilder-ci-openstack"
description = "Minimal Image Builder OpenStack CI image"
version = "0.0.1"

[[packages]]
name = "java-11-openjdk-headless"

[[packages]]
name = "chrony"

[customizations.timezone]
timezome = "UTC"
ntpservers = ["clock.corp.redhat.com"]