name = "imagebuilder-ci-openstack"
description = "Minimal Image Builder OpenStack CI image"
version = "0.0.1"

[[packages]]
name = "java-11-openjdk-headless"

[[packages]]
name = "chrony"

[customizations.services]
enabled = ["sshd", "cloud-init", "cloud-init-local", "cloud-config", "cloud-final"]

[customizations.timezone]
timezome = "UTC"
ntpservers = ["clock.corp.redhat.com"]
